language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
before_install:
  - brew install libffi
env:
  global:
    - PINS="fsevents.dev:. fsevents-lwt.dev:."
matrix:
  include:
    - os: osx
      env: OCAML_VERSION=4.07 PACKAGE="fsevents"
    - os: osx
      env: OCAML_VERSION=4.08 PACKAGE="fsevents-lwt"
